# ---------------------------
# 🔹 Dockerfile
# ---------------------------
# Path: ananta-docker/Dockerfile
FROM nginx:alpine

# Copy custom nginx config
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80